<?php

namespace App\Filament\Resources\RegistrationCodeResource\Pages;

use App\Enums\CodeStatus;
use App\Filament\Resources\RegistrationCodeResource;
use Filament\Resources\Pages\ListRecords;
use Filament\Resources\Pages\ListRecords\Tab;
use Illuminate\Database\Eloquent\Builder;

//class ListRegistrationCodes extends ListRecords
//{
//    protected static string $resource = RegistrationCodeResource::class;
//
//    protected function getHeaderActions(): array
//    {
//        return []; // Codes are generated by payment flows only
//    }
//
//    public function getTabs(): array
//    {
//        return [
//            'all'     => Tab::make('All'),
//            'active'  => Tab::make('Active')
//                ->modifyQueryUsing(fn ($query) => $query->where('status', CodeStatus::ACTIVE))
//                ->badge(fn () => \App\Models\RegistrationCode::where('status', CodeStatus::ACTIVE)->count())
//                ->badgeColor('success'),
//            'pending' => Tab::make('Pending Payment')
//                ->modifyQueryUsing(fn ($query) => $query->where('status', CodeStatus::PENDING))
//                ->badge(fn () => \App\Models\RegistrationCode::where('status', CodeStatus::PENDING)->count())
//                ->badgeColor('warning'),
//            'claimed' => Tab::make('Claimed')
//                ->modifyQueryUsing(fn ($query) => $query->where('status', CodeStatus::CLAIMED)),
//            'expired' => Tab::make('Expired')
//                ->modifyQueryUsing(fn ($query) => $query->where('status', CodeStatus::EXPIRED)),
//        ];
//    }
//
//}

class ListRegistrationCodes extends ListRecords
{
    protected static string $resource = RegistrationCodeResource::class;

    protected function getHeaderActions(): array
    {
        return []; // Codes are generated by payment flows only
    }

    /**
     * Scope the base query so church coordinators only see codes
     * belonging to their church members.
     * Accountants and super_admins see everything.
     */
    protected function getTableQuery(): Builder
    {
        $query = parent::getTableQuery();
        $user  = auth()->user();

        if ($user->hasRole('church_coordinator') && $user->church_id) {
            $query->where('prefill_church_id', $user->church_id);
        }

        return $query;
    }

    public function getTabs(): array
    {
        $user          = auth()->user();
        $isCoordinator = $user->hasRole('church_coordinator');

        // Base scope for badge counts — coordinators only count their church's codes
        $base = \App\Models\RegistrationCode::query()
            ->when($isCoordinator && $user->church_id,
                fn ($q) => $q->where('prefill_church_id', $user->church_id)
            );

        return [
            'all'     => Tab::make('All'),

            'active'  => Tab::make('Active')
                ->modifyQueryUsing(fn ($query) => $query->where('status', CodeStatus::ACTIVE))
                ->badge((clone $base)->where('status', CodeStatus::ACTIVE)->count() ?: null)
                ->badgeColor('success'),

            'pending' => Tab::make('Pending Payment')
                ->modifyQueryUsing(fn ($query) => $query->where('status', CodeStatus::PENDING))
                ->badge((clone $base)->where('status', CodeStatus::PENDING)->count() ?: null)
                ->badgeColor('warning'),

            'claimed' => Tab::make('Claimed')
                ->modifyQueryUsing(fn ($query) => $query->where('status', CodeStatus::CLAIMED)),

            'expired' => Tab::make('Expired')
                ->modifyQueryUsing(fn ($query) => $query->where('status', CodeStatus::EXPIRED)),
        ];
    }
}
