<?php

namespace App\Filament\Resources\RegistrationCodeResource\Pages;

use App\Enums\CodeStatus;
use App\Filament\Resources\RegistrationCodeResource;
use Filament\Resources\Pages\ListRecords;
use Filament\Resources\Pages\ListRecords\Tab;
use Illuminate\Database\Eloquent\Builder;

class ListRegistrationCodes extends ListRecords
{
    protected static string $resource = RegistrationCodeResource::class;

    protected function getHeaderActions(): array
    {
        return []; // Codes are generated by payment flows only
    }

    public function getTabs(): array
    {
        return [
            'all'     => Tab::make('All'),
            'active'  => Tab::make('Active')
                ->modifyQueryUsing(fn ($q) => $q->where('status', CodeStatus::ACTIVE))
                ->badge(fn () => \App\Models\RegistrationCode::where('status', CodeStatus::ACTIVE)->count())
                ->badgeColor('success'),
            'pending' => Tab::make('Pending Payment')
                ->modifyQueryUsing(fn ($q) => $q->where('status', CodeStatus::PENDING))
                ->badge(fn () => \App\Models\RegistrationCode::where('status', CodeStatus::PENDING)->count())
                ->badgeColor('warning'),
            'claimed' => Tab::make('Claimed')
                ->modifyQueryUsing(fn ($q) => $q->where('status', CodeStatus::CLAIMED)),
            'expired' => Tab::make('Expired')
                ->modifyQueryUsing(fn ($q) => $q->where('status', CodeStatus::EXPIRED)),
        ];
    }
}
